//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechEquip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderdetail
    {
        public int id { get; set; }
        public Nullable<int> id_orders { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> total_price { get; set; }
        public Nullable<decimal> discount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
